graph TD
    OPERATOR["OPERATOR"]
    ITEM["ITEM"]
    TAG["TAG"]
    COLLECTION["COLLECTION"]
    SEARCH["SEARCH"]
    MESSAGE["MESSAGE"]

    GERER_ITEM(("GÉRER"))
    POSSEDER(("POSSEDER"))
    ASSIGNER(("ASSIGNER"))
    TAGUER(("TAGUER"))
    CONTENIR(("CONTENIR"))
    GERER_TAG(("GÉRER"))
    CATEGORISER(("CATÉGORISER"))
    THEMATISER(("THÉMATISER"))
    GROUPER(("GROUPE"))

    OPERATOR -->|"0,N"| GERER_ITEM
    GERER_ITEM -->|"1,1"| ITEM

    OPERATOR -->|"0,N"| GERER_TAG
    GERER_TAG -->|"1,1"| TAG

    OPERATOR -->|"0,N"| POSSEDER
    POSSEDER -->|"1,1"| COLLECTION

    OPERATOR -->|"0,N"| ASSIGNER
    ASSIGNER -->|"0,1"| MESSAGE

    ITEM     -->|"0,N"| TAGUER
    TAGUER   -->|"0,N"| TAG

    COLLECTION -->|"0,N"| CONTENIR
    CONTENIR   -->|"0,N"| ITEM

    ITEM -->|"1,1"| CATEGORISER
    CATEGORISER -->|"0,N"| TAG

    ITEM -->|"1,1"| THEMATISER
    THEMATISER -->|"0,N"| TAG

    TAG -->|"0,1"| GROUPER 
    GROUPER -->|"0,N"| TAG 
